// cafe-recomp: translate an RPX into a C++ project, one function per guest
// function. See docs/ARCHITECTURE.md.

#include "codegen.h"
#include "program.h"
#include "rpx.h"

#include <openssl/evp.h>

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <format>
#include <fstream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

using namespace cafe;
namespace fs = std::filesystem;

namespace {

std::string sha256_file(const fs::path& path) {
    std::ifstream input(path, std::ios::binary);
    const std::vector<char> data{std::istreambuf_iterator<char>(input), {}};
    unsigned char digest[32];
    unsigned int length = 0;
    EVP_Digest(data.data(), data.size(), digest, &length, EVP_sha256(), nullptr);
    std::string hex;
    for (unsigned int i = 0; i < length; ++i) {
        hex += std::format("{:02x}", digest[i]);
    }
    return hex;
}

// Rewrites only when the content changed, so unchanged shards keep their
// timestamps and are not recompiled.
bool write_if_changed(const fs::path& path, const std::string& content) {
    std::ifstream existing(path, std::ios::binary);
    if (existing) {
        std::ostringstream current;
        current << existing.rdbuf();
        if (current.str() == content) {
            return false;
        }
    }
    const fs::path temporary = path.string() + ".tmp";
    {
        std::ofstream output(temporary, std::ios::binary);
        output << content;
        if (!output) {
            throw std::runtime_error("cannot write " + temporary.string());
        }
    }
    fs::rename(temporary, path);
    return true;
}

struct Options {
    fs::path rpx;
    fs::path output;
    bool all = false;
    bool comments = true;
    size_t shard_instructions = 24000;
    std::vector<std::pair<uint32_t, uint32_t>> only; // address ranges, for tests
};

const char* kHeader =
    "// Generated by cafe-recomp. Do not edit: replace a function by defining\n"
    "// it elsewhere (see runtime/include/cafe/ppc_ops.h).\n";

int run(const Options& options) {
    const auto started = std::chrono::steady_clock::now();
    const std::string digest = sha256_file(options.rpx);
    const recomp::Program program = recomp::Program::analyze(rpx::load(options.rpx));

    std::vector<const recomp::Entry*> chosen;
    size_t reachable = 0;
    for (const auto& [address, entry] : program.entries) {
        reachable += entry.reachable;
        bool wanted = options.all || entry.reachable;
        if (!options.only.empty()) {
            wanted = std::any_of(options.only.begin(), options.only.end(),
                                 [&](const auto& range) {
                                     return address >= range.first && address < range.second;
                                 });
        }
        if (wanted) {
            chosen.push_back(&entry);
        }
    }

    // Group entries into shards of roughly equal instruction counts.
    std::vector<std::vector<const recomp::Entry*>> shards(1);
    size_t in_shard = 0;
    for (const recomp::Entry* entry : chosen) {
        const size_t words = program.functions[entry->function].size / 4;
        if (in_shard != 0 && in_shard + words > options.shard_instructions) {
            shards.emplace_back();
            in_shard = 0;
        }
        shards.back().push_back(entry);
        in_shard += words;
    }

    fs::create_directories(options.output);
    std::vector<std::string> shard_names(shards.size());
    std::vector<int> changed(shards.size());
    const recomp::EmitOptions emit{options.comments};
    const auto emit_shard = [&](size_t index) {
        std::set<std::string> referenced;
        std::set<std::string> defined;
        std::string bodies;
        for (const recomp::Entry* entry : shards[index]) {
            defined.insert(recomp::function_name(entry->address));
            bodies += recomp::emit_entry(program, *entry, emit, referenced);
        }
        std::string text = kHeader;
        text += "#include \"cafe/ppc_ops.h\"\n\nnamespace ppc = ::cafe::ppc;\n\n";
        for (const auto& name : defined) {
            text += std::format("PPC_WEAK_ALIAS({});\n", name);
        }
        text += "\n";
        for (const auto& name : referenced) {
            if (!defined.count(name)) {
                text += std::format("PPC_FUNC({});\n", name);
            }
        }
        text += "\n" + bodies;
        shard_names[index] = std::format("shard_{:04}.cpp", index);
        changed[index] = write_if_changed(options.output / shard_names[index], text);
    };
    {
        const unsigned workers = std::max(1u, std::thread::hardware_concurrency());
        std::vector<std::thread> threads;
        std::atomic<size_t> next{0};
        for (unsigned t = 0; t < workers; ++t) {
            threads.emplace_back([&] {
                for (size_t i; (i = next.fetch_add(1)) < shards.size();) {
                    emit_shard(i);
                }
            });
        }
        for (auto& thread : threads) {
            thread.join();
        }
    }

    // Indirect-call table: every entry, compiled or not, so a call into
    // something left out is reported by address instead of crashing blindly.
    std::set<uint32_t> compiled;
    for (const recomp::Entry* entry : chosen) {
        compiled.insert(entry->address);
    }
    std::string table = kHeader;
    table += "#include \"cafe/generated.h\"\n#include \"cafe/ppc_ops.h\"\n\n";
    for (const uint32_t address : compiled) {
        table += std::format("PPC_FUNC({});\n", recomp::function_name(address));
    }
    table += "\nextern \"C\" const cafe::GuestFunction cafe_guest_functions[] = {\n";
    for (const auto& [address, entry] : program.entries) {
        table += compiled.count(address)
                     ? std::format("\t{{0x{:08X}u, {}}},\n", address,
                                   recomp::function_name(address))
                     : std::format("\t{{0x{:08X}u, nullptr}},\n", address);
    }
    table += std::format("}};\nextern \"C\" const size_t cafe_guest_function_count = {};\n",
                         program.entries.size());
    write_if_changed(options.output / "function_table.cpp", table);

    // Imports: weak defaults that stop with a clear message; the runtime
    // provides strong definitions as it implements each one.
    std::string imports = kHeader;
    imports += "#include \"cafe/generated.h\"\n#include \"cafe/ppc_ops.h\"\n\n";
    for (const auto& import : program.image.imports) {
        if (import.is_data) {
            continue;
        }
        const std::string& symbol = program.import_symbols.at(import.stub_address);
        imports += std::format(
            "extern \"C\" __attribute__((weak)) void {}(::cafe::PPCContext& ctx, uint8_t*) {{\n"
            "\tcafe_unimplemented_import(ctx, \"{}\", \"{}\");\n}}\n",
            symbol, import.module, import.name);
    }
    imports += "\nextern \"C\" const cafe::GuestImport cafe_guest_imports[] = {\n";
    for (const auto& import : program.image.imports) {
        imports += std::format(
            "\t{{\"{}\", \"{}\", 0x{:08X}u, 0x{:08X}u, {}, {}}},\n", import.module, import.name,
            import.stub_address, import.address,
            import.is_data ? "nullptr" : program.import_symbols.at(import.stub_address),
            import.is_data);
    }
    imports += std::format("}};\nextern \"C\" const size_t cafe_guest_import_count = {};\n",
                           program.image.imports.size());
    const auto& fi = program.image.file_info;
    imports += std::format(
        "\nextern \"C\" const cafe::ProgramInfo cafe_program_info = {{\n"
        "\t\"{}\", 0x{:08X}u, 0x{:08X}u, 0x{:08X}u, 0x{:X}u, 0x{:X}u, {}, {}}};\n",
        digest, program.image.entry_point, fi.sda_base, fi.sda2_base, fi.stack_size,
        fi.heap_size, compiled.size(), program.entries.size());
    write_if_changed(options.output / "imports.cpp", imports);

    std::string cmake = "# Generated by cafe-recomp.\nset(CAFE_GENERATED_SOURCES\n";
    for (const auto& name : shard_names) {
        cmake += "\t${CMAKE_CURRENT_LIST_DIR}/" + name + "\n";
    }
    cmake += "\t${CMAKE_CURRENT_LIST_DIR}/function_table.cpp\n"
             "\t${CMAKE_CURRENT_LIST_DIR}/imports.cpp)\n";
    write_if_changed(options.output / "sources.cmake", cmake);

    // Remove shards left over from a previous, larger run.
    for (size_t index = shards.size();; ++index) {
        const fs::path stale = options.output / std::format("shard_{:04}.cpp", index);
        if (!fs::exists(stale)) {
            break;
        }
        fs::remove(stale);
    }

    size_t words = 0;
    for (const recomp::Entry* entry : chosen) {
        words += program.functions[entry->function].size / 4;
    }
    const auto seconds = std::chrono::duration<double>(std::chrono::steady_clock::now() - started).count();
    std::printf("rpx sha256 %s\n", digest.c_str());
    std::printf("entries: %zu total, %zu reachable, %zu emitted (%zu instructions)\n",
                program.entries.size(), reachable, chosen.size(), words);
    std::printf("shards: %zu (%d rewritten) in %.1f s\n", shards.size(),
                static_cast<int>(std::count(changed.begin(), changed.end(), 1)), seconds);
    return 0;
}

} // namespace

int main(int argc, char** argv) {
    Options options;
    std::vector<std::string> positional;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--all") {
            options.all = true;
        } else if (arg == "--no-comments") {
            options.comments = false;
        } else if (arg == "--shard-instructions" && i + 1 < argc) {
            options.shard_instructions = std::stoul(argv[++i]);
        } else if (arg == "--only" && i + 1 < argc) {
            // --only 0x02000000-0x02100000
            const std::string range = argv[++i];
            const size_t dash = range.find('-');
            options.only.emplace_back(std::stoul(range.substr(0, dash), nullptr, 0),
                                      std::stoul(range.substr(dash + 1), nullptr, 0));
        } else if (!arg.empty() && arg[0] == '-') {
            std::fprintf(stderr, "unknown option %s\n", arg.c_str());
            return 2;
        } else {
            positional.push_back(arg);
        }
    }
    if (positional.size() != 2) {
        std::fprintf(stderr,
                     "usage: %s Tekken.rpx OUTPUT_DIR [--all] [--no-comments]\n"
                     "       [--shard-instructions N] [--only LO-HI]...\n",
                     argv[0]);
        return 2;
    }
    options.rpx = positional[0];
    options.output = positional[1];
    try {
        return run(options);
    } catch (const std::exception& error) {
        std::fprintf(stderr, "error: %s\n", error.what());
        return 1;
    }
}
