// cafe-semgen: emit single-instruction test functions for the semantics
// test. Samples up to N distinct encodings of every instruction variant the
// game actually uses, so the test exercises the real operand combinations.

#include "codegen.h"
#include "ppc.h"
#include "program.h"
#include "rpx.h"

#include <cstdio>
#include <format>
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>

using namespace cafe;

namespace {

// Control flow, traps, reservations, timing, cache maintenance and
// supervisor state are tested elsewhere or have no comparable effect.
bool testable(uint32_t w) {
    using ppc::Op;
    switch (ppc::decode(w)) {
    case Op::invalid: case Op::count:
    case Op::b: case Op::bc: case Op::bclr: case Op::bcctr:
    case Op::sc: case Op::rfi: case Op::tw: case Op::twi: case Op::tdi:
    case Op::mftb: case Op::mfmsr: case Op::mtmsr: case Op::mfsr: case Op::mtsr:
    case Op::mfsrin: case Op::mtsrin: case Op::tlbie: case Op::tlbsync:
    case Op::eciwx: case Op::ecowx: case Op::mffs: case Op::mtfsf: case Op::mtfsfi:
    case Op::mtfsb0: case Op::mtfsb1: case Op::mcrfs:
    case Op::lwarx: case Op::stwcx:
    case Op::sync: case Op::isync: case Op::eieio:
    case Op::dcbf: case Op::dcbi: case Op::dcbst: case Op::dcbt: case Op::dcbtst:
    case Op::icbi:
        return false;
    case Op::mfspr: case Op::mtspr: {
        const uint32_t spr = ppc::spr(w);
        return spr == 1 || spr == 8 || spr == 9 || (spr >= 896 && spr < 904) ||
               (spr >= 912 && spr < 920);
    }
    default:
        return true;
    }
}

std::string variant(uint32_t w) {
    const ppc::Op op = ppc::decode(w);
    std::string name = ppc::op_name(op);
    if (ppc::has_overflow_form(op) && ppc::oe(w)) name += 'o';
    if (ppc::has_record_form(op) && ppc::rc(w)) name += '.';
    return name;
}

uint32_t mix(uint32_t x) {
    x ^= x >> 16; x *= 0x7FEB352Du; x ^= x >> 15; x *= 0x846CA68Bu; x ^= x >> 16;
    return x;
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 3 && argc != 4) {
        std::fprintf(stderr, "usage: %s Tekken.rpx OUTPUT.cpp [per-variant]\n", argv[0]);
        return 2;
    }
    const size_t per_variant = argc == 4 ? std::stoul(argv[3]) : 48;
    try {
        const recomp::Program game = recomp::Program::analyze(rpx::load(argv[1]));
        // Keep, per variant, the encodings with the smallest hashes: a
        // deterministic, spread-out sample.
        std::map<std::string, std::set<std::pair<uint32_t, uint32_t>>> samples;
        for (const auto& function : game.functions) {
            for (uint32_t a = function.address; a < function.address + function.size; a += 4) {
                const uint32_t w = game.word(a);
                if (!testable(w)) continue;
                auto& set = samples[variant(w)];
                set.insert({mix(w), w});
                if (set.size() > per_variant) set.erase(std::prev(set.end()));
            }
        }
        std::vector<uint32_t> words;
        std::vector<uint32_t> tested;
        for (const auto& [name, set] : samples) {
            for (const auto& [hash, w] : set) {
                words.push_back(w);
                words.push_back(0x4E800020); // blr
                tested.push_back(w);
            }
        }
        constexpr uint32_t kBase = 0x01000000;
        const recomp::Program program = recomp::Program::synthetic(kBase, words, 2);
        std::string out =
            "// Generated by cafe-semgen.\n#include \"cafe/ppc_ops.h\"\n\n"
            "namespace ppc = ::cafe::ppc;\n\n";
        std::set<std::string> referenced;
        const recomp::EmitOptions options{true};
        for (const auto& [address, entry] : program.entries) {
            out += recomp::emit_entry(program, entry, options, referenced);
        }
        out += "struct SemanticsTest { uint32_t word; ::cafe::PPCFunc* function; };\n"
               "extern const SemanticsTest kSemanticsTests[] = {\n";
        for (size_t i = 0; i < tested.size(); ++i) {
            out += std::format("\t{{0x{:08X}u, {}_orig}},\n", tested[i],
                               recomp::function_name(kBase + static_cast<uint32_t>(i) * 8));
        }
        out += std::format("}};\nextern const size_t kSemanticsTestCount = {};\n", tested.size());
        std::ofstream(argv[2], std::ios::binary) << out;
        std::printf("%zu variants, %zu encodings\n", samples.size(), tested.size());
        return 0;
    } catch (const std::exception& error) {
        std::fprintf(stderr, "error: %s\n", error.what());
        return 1;
    }
}
